/**
 * Constants
 */
export default {
  APPTENTIVE_APP_STORE_RATING_BLOCKED: 'apptentive:app-store-rating:blocked',
  APPTENTIVE_APP_STORE_RATING_ERROR: 'apptentive:app-store-rating:error',
  APPTENTIVE_APP_STORE_RATING_OPEN_APP_STORE_URL: 'apptentive:app-store-rating:open-app-store-url',
  APPTENTIVE_ERROR: 'apptentive:error',
  APPTENTIVE_INIT: 'apptentive:init',
  APPTENTIVE_READY: 'apptentive:ready',
  APPTENTIVE_LOVE_DIALOG_CANCEL: 'apptentive:love-dialog:cancel',
  APPTENTIVE_LOVE_DIALOG_CLOSE: 'apptentive:love-dialog:close',
  APPTENTIVE_LOVE_DIALOG_DISMISS: 'apptentive:love-dialog:dismiss',
  APPTENTIVE_LOVE_DIALOG_ERROR: 'apptentive:love-dialog:error',
  APPTENTIVE_LOVE_DIALOG_LAUNCH: 'apptentive:love-dialog:launch',
  APPTENTIVE_LOVE_DIALOG_NO: 'apptentive:love-dialog:no',
  APPTENTIVE_LOVE_DIALOG_YES: 'apptentive:love-dialog:yes',
  APPTENTIVE_MESSAGE_CENTER_CLOSE: 'apptentive:message-center:close',
  APPTENTIVE_MESSAGE_CENTER_DISMISS: 'apptentive:message-center:dismiss',
  APPTENTIVE_MESSAGE_CENTER_ERROR: 'apptentive:message-center:error',
  APPTENTIVE_MESSAGE_CENTER_LAUNCH: 'apptentive:message-center:launch',
  APPTENTIVE_MESSAGE_CENTER_SEND: 'apptentive:message-center:send',
  APPTENTIVE_MESSAGES_CREATED: 'apptentive:messages:created',
  APPTENTIVE_MESSAGES_FETCHED: 'apptentive:messages:fetched',
  APPTENTIVE_NAVIGATE_TO_LINK_BLOCKED: 'apptentive:navigate-to-link:blocked',
  APPTENTIVE_NAVIGATE_TO_LINK_ERROR: 'apptentive:navigate-to-link:error',
  APPTENTIVE_NAVIGATE_TO_LINK_NAVIGATE: 'apptentive:navigate-to-link:navigate',
  APPTENTIVE_NAVIGATE_TO_LINK_NAVIGATED: 'apptentive:navigate-to-link:navigated',
  APPTENTIVE_NOTE_CANCEL: 'apptentive:note:cancel',
  APPTENTIVE_NOTE_CLICK: 'apptentive:note:click',
  APPTENTIVE_NOTE_CLOSE: 'apptentive:note:close',
  APPTENTIVE_NOTE_DISMISS: 'apptentive:note:dismiss',
  APPTENTIVE_NOTE_ERROR: 'apptentive:note:error',
  APPTENTIVE_NOTE_LAUNCH: 'apptentive:note:launch',
  APPTENTIVE_OVERLAY_CLICK: 'apptentive:overlay:click',
  APPTENTIVE_RENDER_INTERACTION: 'apptentive:render:interaction',
  APPTENTIVE_SURVEY_DISMISS: 'apptentive:survey:dismiss',
  APPTENTIVE_SURVEY_ERROR: 'apptentive:survey:error',
  APPTENTIVE_SURVEY_LAUNCH: 'apptentive:survey:launch',
  APPTENTIVE_SURVEY_SUBMIT: 'apptentive:survey:submit',
  APPTENTIVE_SURVEY_NEXT_QUESTION_SET: 'apptentive:survey:next_question_set',
};
