/**
 * Constants
 */
export default {
  APPTENTIVE_APP_STORE_RATING_LAUNCH: 'com.apptentive#AppStoreRating#launch',
  APPTENTIVE_APP_STORE_RATING_OPEN_APP_STORE_URL: 'com.apptentive#AppStoreRating#open_app_store_url',
  APPTENTIVE_APP_STORE_RATING_UNABLE_TO_RATE: 'com.apptentive#AppStoreRating#unable_to_rate',
  APPTENTIVE_INIT: 'com.apptentive#app#init',
  APPTENTIVE_LAUNCH: 'com.apptentive#app#launch',
  APPTENTIVE_LOVE_DIALOG_CANCEL: 'com.apptentive#EnjoymentDialog#cancel',
  APPTENTIVE_LOVE_DIALOG_DISMISS: 'com.apptentive#EnjoymentDialog#dismiss',
  APPTENTIVE_LOVE_DIALOG_LAUNCH: 'com.apptentive#EnjoymentDialog#launch',
  APPTENTIVE_LOVE_DIALOG_NO: 'com.apptentive#EnjoymentDialog#no',
  APPTENTIVE_LOVE_DIALOG_YES: 'com.apptentive#EnjoymentDialog#yes',
  APPTENTIVE_MESSAGE_CENTER_CLOSE: 'com.apptentive#MessageCenter#close',
  APPTENTIVE_MESSAGE_CENTER_LAUNCH: 'com.apptentive#MessageCenter#launch',
  APPTENTIVE_MESSAGE_CENTER_SEND: 'com.apptentive#MessageCenter#send',
  APPTENTIVE_NAVIGATE_TO_LINK_NAVIGATE: 'com.apptentive#NavigateToLink#navigate',
  APPTENTIVE_NOTE_CANCEL: 'com.apptentive#TextModal#cancel',
  APPTENTIVE_NOTE_CLICK_INTERACTION: 'com.apptentive#TextModal#interaction',
  APPTENTIVE_NOTE_DISMISS: 'com.apptentive#TextModal#dismiss',
  APPTENTIVE_NOTE_LAUNCH: 'com.apptentive#TextModal#launch',
  APPTENTIVE_SURVEY_CANCEL: 'com.apptentive#Survey#cancel',
  APPTENTIVE_SURVEY_CANCEL_PARTIALLY: 'com.apptentive#Survey#cancel_partial',
  APPTENTIVE_SURVEY_CLOSE: 'com.apptentive#Survey#close',
  APPTENTIVE_SURVEY_LAUNCH: 'com.apptentive#Survey#launch',
  APPTENTIVE_SURVEY_SUBMIT: 'com.apptentive#Survey#submit',
  APPTENTIVE_SURVEY_NEXT_QUESTION_SET: 'com.apptentive#Survey#next_question_set',
  APPTENTIVE_SURVEY_QUESTION_SET_SHOWN: 'com.apptentive#Survey#question_set_shown',
};
